### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by bronzeblood** [JustusUlbrich/Leuchtknoten#1]
I'm getting an error when compiling. 

`.pio\libdeps\az-delivery-devkit-v4\ArduinoJson\src/ArduinoJson/Variant/VariantRef.hpp:253:34: error: invalid use of incomplete type 'class ArduinoJson6183_91::InvalidConversion<ArduinoJson6183_91::VariantConstRef, ArduinoJson6183_91::ArrayRef>'
     return Converter<T>::fromJson(*this);
                                  ^
In file included from .pio\libdeps\az-delivery-devkit-v4\ArduinoJson\src/ArduinoJson/Variant/VariantRef.hpp:14:0,
                 from .pio\libdeps\az-delivery-devkit-v4\ArduinoJson\src/ArduinoJson/Array/ArrayIterator.hpp:8,
                 from .pio\libdeps\az-delivery-devkit-v4\ArduinoJson\src/ArduinoJson/Array/ArrayRef.hpp:8,
                 from .pio\libdeps\az-delivery-devkit-v4\ArduinoJson\src/ArduinoJson.hpp:17,
                 from .pio\libdeps\az-delivery-devkit-v4\ArduinoJson\src/ArduinoJson.h:9,
                 from .pio\libdeps\az-delivery-devkit-v4\ESP Async WebServer\src/AsyncJson.h:37,
                 from src\main.cpp:8:
.pio\libdeps\az-delivery-devkit-v4\ArduinoJson\src/ArduinoJson/Variant/Converter.hpp:14:7: note: declaration of 'class ArduinoJson6183_91::InvalidConversion<ArduinoJson6183_91::VariantConstRef, ArduinoJson6183_91::ArrayRef>'
 class InvalidConversion;  // Error here? See https://arduinojson.org/v6/invalid-conversion/
       ^`

**Comment by bronzeblood** [comment]
OK i found if i change line 19 in config_json.hpp from `auto ledInfo = src["led_info"].as<JsonArray>(); ` to  `auto ledInfo = src["led_info"].as<JsonArrayConst>(); `  

It will compile but leds dont change and i cant edit anything in the settings menu.

**Comment by JustusUlbrich** [comment]
I completely missed your issue, sry. 

I was using a slightly modified version of arduinoJson, but I could reproduce the bug on another machine. It should be fixed with the changes you mentioned. Thanks :)

> It will compile but leds dont change and i cant edit anything in the settings menu.

I suspect this is due to the IP adress, that is currently still hard coded in the UI project: https://github.com/JustusUlbrich/Leuchtknoten-ui#usage

You proably have to change it and rebuild the frontend (or you might edit this manually in index.html ;) )

**Comment by JustusUlbrich** [comment]
I added another quick fix and replaced the hard coded IP address by a fixed hostname, so the frontend should be able to access the esp without change.

Just add the hostname parameter to your config (with hostname: "Leuchtknoten") and reupload it.
